Replace c++11 constexpr with c++98 external initialization (#10)
This fixes the following compile error on Ubuntu 14.04 / Indigo:

    include/diffdrive_gazebo_plugin/gazebo_ros_diffdrive_uos.h:28:10: error: 'constexpr' does not name a type
       static constexpr double CMD_VEL_TIMEOUT = 0.6;

The problem is that 66aab37 introduced this C++11 feature, but 9edd4c8
replaced `add_compile_options(-std=c++11)` with `GAZEBO_CXX_FLAGS`.
However, `GAZEBO_CXX_FLAGS` is empty on Indigo (it works on Jade).